from . import product_sub_category
from . import product_template
from . import purchase_order
from . import inv_plan
from . import inv_plan_tmpl
from . import inv_plan_line
from . import res_config_settings
from . import res_partner
from . import res_users
from . import product_sale_history
from . import product_purchase_history
