{
    'name': 'Guía de Remisión para Ecuador en Inventario',
    'version': '16.0.1.0.0',
    'category': 'Localization/Ecuador',
    'summary': 'Integración de Guía de Remisión dentro del módulo de Inventario',
    'description': 'Este módulo extiende la funcionalidad del Inventario en Odoo para manejar Guías de Remisión en Ecuador.',
    'author': 'Washington Guijarro',
    'website': 'https://tuwebsite.com',
    'depends': ['stock','account_payment_purchase','account','fleet','analytic','purchase_request'],
    'data': [
        "data/guia_authorization_template.xml",
        "templates/edi_document_guiaremision.xml",
        'views/std_reason_document.xml',
        'views/guide_remission_view.xml',
        'views/account_views.xml',
        'data/sequence_data.xml',
        'report/report_stockpicking_operations_gps.xml',
        'report/report.xml',
        'report/report_guide_remission.xml',
        'security/ir.model.access.csv',
    ],
    'installable': True,
    'application': False,
}
