{
    'name': 'Construcción',
    'version': '1.0',
    'category': 'Construcción',
    'summary': 'Módulo para gestionar presupuestos con análisis de precios unitarios (APU).',
    'description': 'Gestiona presupuestos de construcción y calcula los costos utilizando los APU.',
    'author': 'GPS Group',
    'depends': [
        'base','account','mrp','portal','sale','stock','uom','hr_timesheet','sale_project','macro_purchase_request','material_purchase_requisitions','purchase_request'
    ],
    'assets': {
            'web.assets_backend': [
                'construccion_gps/static/src/css/custom_styles.css',
            ],
        },
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/mail_template_data.xml',
        # 'views/budget_views.xml',
        'views/purchase_requisitions.xml',
         'views/product_template_view.xml',
         'views/apu_views.xml',
         'views/sale_order_view.xml',
         'views/bim_configuracion_view.xml',
         'views/tarea_views.xml',
         'views/apu_tareas_views.xml',
         'views/plantilla_tareas_views.xml',
         'views/categorias_apu_view.xml',
         'views/apu_apu_tags.xml',
         'views/tipo_presupuesto.xml',
        # 'views/budget_line_views.xml',
        #'views/apu_line_views.xml',
        'views/project_views.xml',
        # 'views/subproject_views.xml',
        'wizard/sale_order_wizard.xml',
        'wizard/plantilla_tareas_wizard.xml',
        'views/menu_views.xml',
        'views/material_requisition_blocked.xml',
        'report/informe_detallado.xml',
        # 'report/informe_detallado_mo.xml',
        'report/informe_detallado_mo_consolidado.xml',
        # 'report/informe_detallado_ma.xml',
        'report/informe_detallado_ma_consolidado.xml',
        'report/informe_detallado_ma_consolidado_or_alfabetico.xml',
        'report/informe_detallado_apu.xml',
        'report/informe_detallado_apu_secciones.xml',
        'report/informe_detallado_apus_secciones.xml',
        'report/informe_detallado_sin_valores.xml',
        'report/informe_detallado_mo_consolidado_sin_valores.xml', 
        'report/informe_detallado_ma_consolidado_sin_valores.xml',
        # 'data/data.xml',
    ],
    'images': [
        'static/description/logo.png',  # Logo del módulo.
        'static/description/icon.png'   # Icono del módulo.
    ],
    'installable': True,
    'application': True,
}
