# Copyright 2016 Akretion (<http://www.akretion.com>).
# Copyright 2017 Tecnativa - Vicent Cubells
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).

{
    "name": "Account Payment Purchase",
    "version": "16.0.2.0.1",
    "category": "Varios GPS",
    "license": "AGPL-3",
    "summary": "Adds Bank Account and Payment Mode on Purchase Orders",
    "author": "Washington Guijarro",
    "website": "https://gpsgroup.com.ec",
    "depends": ["hr_timesheet","material_purchase_requisitions","stock_account","mrp","crm","account_payment_partner", "purchase",'base','account','stock_landed_costs','fleet','stock','l10n_ec','product','sale','purchase_sale_stock_inter_company','product_brand','l10n_ec_edi','account_move_taxes','purchase_analytic','project','portal'],
    "data": ['security/groups.xml',
            'security/ir.model.access.csv',
            #"data/l10n_latam.document.type.csv",
            'data/comprador_purchase_approval_template.xml',
            "views/config_settings_approval_po.xml",
            "wizard/purchase_order_wizard.xml",
             "views/purchase_order_view.xml",
             "views/res_partner_view.xml",
             "views/account_analytic_account.xml",
             "views/centro_costo_nombre_proyecto.xml",
             "views/centro_costo_tipo_proyecto.xml",
             "views/centro_costo_ubicaciones.xml",
             "views/centro_costo_zona.xml",
             "views/clase_importacion_views.xml",
             "views/stock_landed_cost.xml",
             "views/fleet_vehicle_view.xml",
             "views/res_partner_bank_view.xml",
             "views/product_template_view.xml",
             'report/purchase_order_report.xml',
             'report/registro_reembolso_report.xml',
             'report/registro_caja_chica_report.xml',
             "views/sale_order.xml",
             "views/crm_lead_views.xml",
             "views/account_move_views.xml",
             "views/mrp_production.xml",
             "views/registro_reembolsos.xml",
             "views/registro_caja_chica.xml",
             "views/tipo_costo_views.xml",
             ],
    "installable": True,
    "auto_install": True,
}
